source "https://api.berkshelf.com"

cookbook "drupal", github: "joshuacox/drupal-cookbook"
cookbook "vdd", github: "joshuacox/vdd-cookbook"
cookbook "vdd_example", github: "joshuacox/vdd_example-cookbook"
cookbook "apache2", github: "viverae-cookbooks/apache2"
cookbook "apt", github: "opscode-cookbooks/apt"
cookbook "aws", github: "opscode-cookbooks/aws"
cookbook "build-essential", github: "opscode-cookbooks/build-essential"
cookbook "chef_handler", github: "opscode-cookbooks/chef_handler"
cookbook "database", "= 2.2.0"
cookbook "iis", github: "opscode-cookbooks/iis"
cookbook "iptables", github: "opscode-cookbooks/iptables"
cookbook "logrotate", github: "stevendanna/logrotate"
cookbook "mysql", "= 5.2.10"
cookbook "mysql_chef_gem", github: "opscode-cookbooks/mysql_chef_gem"
cookbook 'chef-sugar'
cookbook "openssl", github: "opscode-cookbooks/openssl"
cookbook "pacman", github: "jesseadams/pacman"
cookbook "php", github: "opscode-cookbooks/php"
cookbook "postgresql", github: "hw-cookbooks/postgresql"
cookbook "windows", github: "opscode-cookbooks/windows"
cookbook "xfs", github: "opscode-cookbooks/xfs"
cookbook "xml", github: "opscode-cookbooks/xml"
